local_backend: true
backend:
  name: github
  repo: alansmorais/danielatorp
  branch: main 

media_folder: "wp-content/uploads"
public_folder: "/wp-content/uploads"

collections:
  - name: "content"
    label: "Site Content"
    files:
      - label: "Homepage Text"
        name: "homepage"
        file: "data.json"
        format: "json"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Paragraph 1", name: "hero_p1", widget: "text" }
          - { label: "Hero Paragraph 2", name: "hero_p2", widget: "text" }
          - { label: "About Title", name: "about_title", widget: "string" }
          - { label: "About Paragraph 1", name: "about_p1", widget: "text" }
